version: '3.9'

services:
  api:
    container_name: LaThien_api
    build: .
    command: npm run start:dev
    restart: always
    ports:
      - $API_PORT:$API_PORT
    volumes:
      - .:/home/app
    depends_on:
      - db
    env_file:
      - ./.env
    networks:
      - nest_demo_network

  db:
    container_name: LaThien_postgres
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - $POSTGRES_PORT:5432
    networks:
      - nest_demo_network

  admin:
    container_name: LaThien_db_admin
    image: adminer
    restart: always
    ports:
      - $ADMIN_PORT:8080
    expose:
      - $ADMIN_PORT
    environment:
      - ADMINER_DEFAULT_SERVER=db
    depends_on:
      - db
    networks:
      - nest_demo_network

  redis:
    container_name: LaThien_redis
    image: redis
    restart: always
    command: bash -c "redis-server --appendonly yes --requirepass $REDIS_PASSWORD"
    ports:
      - 6380:6379
    volumes:
      - redis:/data/cache
    networks:
      - nest_demo_network

  redis-gui:
    container_name: LaThien_redis_gui
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    restart: always
    depends_on:
      - redis
    environment:
      - REDIS_HOST
      - REDIS_PASSWORD
      - HTTP_USER=admin
      - HTTP_PASSWORD=admin
    ports:
      - $REDIS_PORT_GUI:8081
    expose:
      - $REDIS_PORT_GUI
    networks:
      - nest_demo_network

  minio:
    container_name: LaThien_minio
    image: minio/minio
    restart: always
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: $MINIO_ACCESS_KEY
      MINIO_ROOT_PASSWORD: $MINIO_SECRET_KEY
    ports:
      - $MINIO_PORT:9000
      - 9001:9001
    volumes:
      - minio-data:/data
    networks:
      - nest_demo_network

volumes:
  postgres-data:
  redis:
    driver: local
  minio-data:

networks:
  nest_demo_network:
    driver: bridge
