version: '3'

services:
  api:
    container_name: CHANGE_ME_api
    build: .
    command: npm run start:dev
    restart: always
    ports:
      - $API_PORT:3000
    volumes:
      - .:/home/app
    env_file:
      - ./.env

  db:
    container_name: CHANGE_ME_db
    image: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD
      - MONGO_INITDB_DATABASE
    volumes:
      - db:/data/db

  admin:
    container_name: CHANGE_ME_db_admin
    image: mongo-express:1.0.0-18-alpine3.18

    restart: always
    ports:
      - $ADMIN_PORT:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=$MONGO_INITDB_ROOT_USERNAME
      - ME_CONFIG_MONGODB_ADMINPASSWORD=$MONGO_INITDB_ROOT_PASSWORD
      - ME_CONFIG_MONGODB_URL=$MONGO_URI
    depends_on:
      - db

  files:
    container_name: CHANGE_ME_db_file
    image: nginx:alpine
    restart: always
    volumes:
      - $FILE_ROOT:/usr/share/nginx/html
    ports:
      - $FILE_PORT:80

  redis:
    container_name: CHANGE_ME_redis
    image: redis
    restart: always
    volumes:
      - redis:/data/cache

  redis-gui:
    container_name: CHANGE_ME_redis_gui
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - $REDIS_PORT_GUI:8081

volumes:
  db:
  redis:
    driver: local
