version: '3.9'

services:
  api:
    container_name: CHANGE_ME_api
    build: .
    command: npm run start:dev
    restart: always
    ports:
      - $API_PORT:$API_PORT
    volumes:
      - .:/home/app
    depends_on:
      - mongo
    env_file:
      - ./.env
    networks:
      - nest_demo_network

  mongo:
    container_name: CHANG_ME_mongo
    image: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD
      - MONGO_INITDB_DATABASE
      - MONGO_HOST
      - MONGO_HOST_1
      - MONGO_HOST_2
    volumes:
      - mongo-data:/data/db
      - ./mongo-setup/rs-init.sh:/scripts/rs-init.sh
    ports:
      - $MONGO_PORT:27017
    entrypoint: ['/usr/bin/mongod', '--bind_ip_all', '--replSet', 'rs0']
    networks:
      - nest_demo_network

  mongo1:
    container_name: CHANG_ME_mongo_1
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD
    depends_on:
      - mongo
    ports:
      - 27031:27017
    restart: always
    entrypoint: ['/usr/bin/mongod', '--bind_ip_all', '--replSet', 'rs0']
    networks:
      - nest_demo_network

  admin:
    container_name: CHANGE_ME_db_admin
    image: mongo-express:1.0.0-18-alpine3.18
    restart: always
    ports:
      - $ADMIN_PORT:8081
    expose:
      - $ADMIN_PORT
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=$MONGO_INITDB_ROOT_USERNAME
      - ME_CONFIG_MONGODB_ADMINPASSWORD=$MONGO_INITDB_ROOT_PASSWORD
      - ME_CONFIG_MONGODB_URL=$MONGO_URI
    depends_on:
      - mongo
    networks:
      - nest_demo_network

  files:
    container_name: CHANGE_ME_db_file
    image: nginx:alpine
    restart: always
    volumes:
      - $FILE_ROOT:/usr/share/nginx/html
    ports:
      - $FILE_PORT:80
    expose:
      - $FILE_PORT
    networks:
      - nest_demo_network

  redis:
    container_name: CHANGE_ME_redis
    image: redis
    restart: always
    command: bash -c "redis-server --appendonly yes --requirepass $REDIS_PASSWORD"
    ports:
      - 6380:6379
    volumes:
      - redis:/data/cache
    networks:
      - nest_demo_network

  redis-gui:
    container_name: CHANGE_ME_redis_gui
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    restart: always
    depends_on:
      - redis
    environment:
      - REDIS_HOST
      - REDIS_PASSWORD
      - HTTP_USER=admin
      - HTTP_PASSWORD=admin
    ports:
      - $REDIS_PORT_GUI:8081
    expose:
      - $REDIS_PORT_GUI
    networks:
      - nest_demo_network

volumes:
  mongo-data:
  redis:
    driver: local

networks:
  nest_demo_network:
    driver: bridge
