version: 2.1
orbs:
  node: circleci/node@5

jobs:
  test-node:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Install
          command: rm -rf node_modules && npm install
      - run:
          name: Run build
          command: npm run build
      - run:
          name: Run test
          command: npm run test
      - run:
          name: Run test:architect
          command: npm run test:architect

  build-image:
    docker:
      - image: node:21
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: "Build the Image"
          command: "make up-prod"

  deploy:
    docker:
      - image: node:21
    steps:
      - run:
          name: Deploy
          command: "Deploying"
          # command: |
          #   ssh -o StrictHostKeyChecking=no \
          #       -o UserKnownHostsFile=/dev/null \
          #       -i ~/.ssh/${{ secrets.SSH_KEY_NAME }} \
          #       ${{ secrets.SSH_USERNAME }}@${{ secrets.SERVER_IP }} \
          #       "cd ${{ secrets.SERVER_PATH }} && make re-deploy"

workflows:
  build-and-test:
    jobs:
      - test-node
      - build-image:
          requires:
            - test-node
      - deploy:
          requires:
            - build-image
          filters:
            branches:
              only:
                - main
