version: 2.1
orbs:
  node: circleci/node@5
jobs:
  test-node:
    executor: node/default
    environment:
      JEST_JUNIT_OUTPUT_DIR: ./test-results/
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Install
          command: npm ci
      - run:
          name: Run build
          command: npm run build
      - run:
          name: Run test
          command: npm run test

  build-image:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: "Build the Image"
          command: "echo 'Building the Image'"

  deploy:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: deploy
          command: "echo 'Deploying'"

workflows:
  build-and-test:
    jobs:
      - test-node
      - build-image:
          requires:
            - test-node
      - deploy:
          requires:
            - build-image
          filters:
            branches:
              only:
                - main
