global:
  scrape_interval: 15s

scrape_configs:
  - job_name: api-service
    scrape_interval: 15s
    scrape_timeout: 10s
    metrics_path: /metrics
    static_configs:
      - targets:
          - "node-exporter:9100"
          - "prometheus:9090"
