name: CI - Nest - Docker

on:
  push:
    branches:
      - "*"
      - "*/*"

jobs:
  install:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Setup Node.js with caching
        uses: actions/setup-node@v4
        with:
          node-version: "21.x"

      - name: Install dependencies and build
        run: |
          npm ci
          npm run build

  test:
    runs-on: ubuntu-22.04
    needs: [install]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Install dependencies and tests
        run: |
          npm run test

  build:
    runs-on: ubuntu-22.04
    needs: [test]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKER_HUB_US}}
          password: ${{secrets.DOCKER_HUB_AT}}

      - name: Build docker image
        run: docker build -t ${{secrets.DOCKER_HUB_US}}/demo-github-action:latest -f Dockerfile.pro .

      - name: Push docker image
        run: docker push ${{secrets.DOCKER_HUB_US}}/demo-github-action:latest

      - name: Update image metadata
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKER_HUB_US }}/demo-github-action:latest
          tags: |
            type=sha
          labels: |
            org.opencontainers.image.title=Base Nest Example
            org.opencontainers.image.description=Example NestJS github action application
            org.opencontainers.image.url=https://github.com/${{github.repository}}
            org.opencontainers.image.revision=${{github.sha}}
            org.opencontainers.image.licenses=MIT
